### ISSUE TITLE
[FEAT] 서버 배포환경 세팅

### ISSUE THREAD

**Issue by PgmJun** [Team-co-re/co-re-server#10]
## Description 📝
설명을 작성해주세요

## To-Do ☑️
- [x] WebMvcConfigure CORS 설정
- [x] AWS EC2 배포환경 설정
- [x] AWS Elasticache 사용하여 Redis 인메모리 DB 연결
- [x] AWS RDS 연결
- [x] AWS SecretsManager 적용하여 환경변수 관리
- [x] local에서 사용할 Redis docker 이미지 docker-compose.yml 파일에 등록
- [x] java KTC로 배포 (CI/CD는 적용 X)
 

## Reference 📚
- Elasticache 관련 설정
  - https://foot-develop.tistory.com/57
  - https://ujin-dev.tistory.com/73
