### ISSUE TITLE
[SETTING] 서버 보안성 개선

### ISSUE THREAD

**Issue by PgmJun** [Team-co-re/co-re-server#20]
## Description 📝
설명을 작성해주세요

## To-Do ☑️
- [x] nginx EC2 생성하여 리버스 프록시 서버 구축
  - [x] Reverse Proxy용 AWS 계정 및 EC2 생성하여 Nginx 리버스프록시 세팅
  - [x] SprinbBoot CORS 설정을 `nginx EC2 IP` 만 허용하여 외부의 직접적인 요청 방어 + WAS 정보 노출 방어
  - [x] 추후에 서버 요청이 많아졌을 때, SpringBoot 애플리케이션을 scale out 후 Load Balancing 할 수 있는 확장성 부여

## Reference 📚
- https://velog.io/@jjonggang/Spring-Boot-Nginx%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%98%EC%97%AC-Spring-Boot%EB%A5%BC-80%EB%B2%88-%ED%8F%AC%ED%8A%B8%EB%A1%9C-%ED%94%84%EB%A1%9D%EC%8B%9C%ED%95%98%EA%B8%B0

**Comment by PgmJun** [comment]
## ReverseProxy To WAS 과정 504 Bad Gateway 문제 해결
https://stackoverflow.com/questions/24453388/nginx-reverse-proxy-causing-504-gateway-timeout
