### ISSUE TITLE
[FEAT] 회원 기능 분리 및 유저 트래픽 제한

### ISSUE THREAD

**Issue by PgmJun** [Team-co-re/co-re-server#25]
## Description 📝
- GPT API가 현재는 무료 호출이다보니까, 악의적으로 요청을 계속보내면 금전적인 문제가 발생할 것으로 예상되어 트래픽 제한을 생각하게 됨. 
  - bucket4j 사용하면 일정시간 혹은 사용자마다 요청한도(트래픽)을 제한할 수 있음
- 회원 기능 비회원 기능 분리
  - 변수명 추천: 비회원 기능, 무제한 호출
  - 타 기능: 회원 기능, 하루 10회 호출

## To-Do ☑️
- [x] bucket4j 적용하여 1분에 5번 요청만 가능하도록 구현
- [x] MemberRole에 따라 요청 가능 횟수 구분
- [ ] GPT관련 API에 대해서만 트래픽 제한하도록 설정

## Reference 📚
https://khj93.tistory.com/entry/Bucket4j%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%9C-Spring-API-%EC%9A%94%EC%B2%AD-%ED%95%9C%EB%8F%84-%ED%8A%B8%EB%9E%98%ED%94%BD-%EC%A0%9C%ED%95%9C%ED%95%98%EA%B8%B0

https://howisitgo1ng.tistory.com/entry/Spring-Boot%EC%97%90-Redis%EC%99%80-%EC%97%B0%EB%8F%99%ED%95%98%EC%97%AC-%EC%B2%98%EB%A6%AC%EC%9C%A8-%EC%A0%9C%ED%95%9C-%EC%9E%A5%EC%B9%98Rate-Limiter-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0Spring-Boot-Redis-Bucket4j
