### ISSUE TITLE
[FEAT] 콘텐츠 추천 기능

### ISSUE THREAD

**Issue by PgmJun** [Team-co-re/co-re-server#26]
## Description 📝
사용자가 정보를 입력하면 그에 해당하는 개발 학습 콘텐츠를 추천한다.

## To-Do ☑️
- [ ] GPT Completion API를 튜닝하여 기능에 맞게 적절한 응답을 하도록 구현
- [ ] 추천 플랫폼(유튜브, 독서, 강의, 블로그) 중 택1 하여 입력받도록 구현
- [ ] 추천받고 싶은 기술 입력받도록 구현

**Comment by PgmJun** [comment]
gpt가 2021년 9월까지의 정보만 가지고 있으며, 대체로 유명한 강의들을 추천하지 않아 좋은 컨텐츠의 추천 기준이 모호하여 해당 기능은 삭제
