### ISSUE TITLE
[FEAT] 회원 요청 내용 즐겨찾기 기능 구현

### ISSUE THREAD

**Issue by PgmJun** [Team-co-re/co-re-server#35]
## Description 📝
마음에 드는 응답 내용이라면 클라이언트의 redux tool-kit에서 보관후 삭제하지 않고
즐겨찾기DB에 저장하여 다시 볼 수 있도록 한다.

## To-Do ☑️
- [x] 응답 즐겨찾기
  - [x] 즐겨찾기 API 개발
    - [x] `기능종류`, `질문내용`, `응답내용`, `질문날짜`를 포함하여 즐겨찾기 API 호출
    - MySQL에서 질문내용과 응답 내용의 메모리 사이즈 동적으로 조정할 수 있도록 Text형 선택
    - [x] 동일한 `기능종류`,`질문내용`,`응답내용`,`질문날짜` 가 Favorite 테이블에 이미 존재하면, 목록에서 삭제하지 않고 즐겨찾기 여부 false로 변경

- [x] 응답 즐겨찾기 삭제
  - 즐겨찾기 목록에서는 즐겨찾기 여부 변경이 아닌 데이터를 실제로 삭제함
  - [x] 즐겨찾기 데이터의 PK를 통해 즐겨찾기 목록에서 삭제

- [x] 즐겨찾기 조회
  - [x] 'memberId', '기능종류' 입력받으면 해당 기능에 대한 즐겨찾기 목록을 '날짜' 순서대로 정렬하여 리턴

**Comment by PgmJun** [comment]
## 고민 내용 : 질문내용과 응답 내용의 사이즈 동적으로 조정할 수 있는 자료형 탐색

MySQL의 Text 유형은 입력값에 따라 동적으로 메모리 공간을 할당하므로, 요청 내용 저장과 같이 데이터의 크기가 다양한 상황에서 사용하기 적합함.
때문에 요청,응답 내용 저장은 Text 자료형을 사용하는 것으로 결정
