### ISSUE TITLE
[FEAT] Domain & HTTPS 적용

### ISSUE THREAD

**Issue by PgmJun** [Team-co-re/co-re-server#43]
## Description 📝
도메인 적용 및 HTTPS를 적용한다.

## To-Do ☑️
- [x] 도메인 구매
- [x] AWS Route53 DNS를 활용하여 구매한 도메인을 적용
- [x] Certification Manager를 통해 SSL 인증서 발급
- [x] Core 서버에 HTTPS 적용
- [x] Health Check API 구현
