### ISSUE TITLE
[REFACTOR] GPT API 튜닝

### ISSUE THREAD

**Issue by PgmJun** [Team-co-re/co-re-server#8]
## Description 📝
- WebClient 환경에서 ChatGpt API를 튜닝하여 요청 속도와 응답 정확도를 개선하자
  - 현재 gpt-3.5-turbo 모델 사용 중

## Why 💭
- 속도 개선: GPT의 응답속도가 빠른 편이 아니기 때문에 더욱 향상시켜 성능을 끌어올릴 수 있는 방법을 탐색하게 됨
- 정확도 개선: 코드에 설명주석을 다는 요청을 요구했는데, 필요없는 부연설명이 함께 응답되는 등 기능의 퀄리티를 낮추는 현상이 계속해서 발생

## To-Do ☑️
- [ ] ChatGPT API 요청 속도 개선
- [x] 요청 정확도 개선
  - [x] 이전 텍스트나 문맥을 기반으로 다음 텍스트를 생성하는 작업인 Completion을 통해, 기능에 필요한 정확한 응답을 받아낼 수 있도록 튜닝

## Reference 📚
- https://aifactory.space/task/2289/discussion/186
- https://firstws.tistory.com/64
- [공식문서] https://platform.openai.com/docs/api-reference/chat/create
- https://www.developerfastlane.com/blog/chatgpt-api-usage-and-prompt-optimization

**Comment by PgmJun** [comment]
속도 개선은 조금 더 학습해서 적용해야할 것 같습니다.
우선 이대로 PR 올려서 기능부터 사용할 수 있도록 하겠습니다.
